import { CountrySpriteImage, CustomIcon } from '@components';
import { ICountryFlag, IMobileNumberInput } from '@interfaces';
import { useDeviceType } from '@utils';
import { useEffect, useRef, useState } from 'react';
import Error from '../Error';
import { FloatingInput } from '../index';
import CountryFlagDropdown from './CountryFlagDropdown';
import styles from './mobileNumberInput.module.scss';

import Image from 'next/image';
import greenTick from '../../../../assets/temp/greeen_tick.svg';

const countries: ICountryFlag[] = [
  {
    countryName: 'India',
    dialCode: '+91',
    isO3: 'IND',
    isO2: 'IN',
    untermEnglish: 'the Republic of India',
    id: '1',
    contactNoLength: '10',
  },
  {
    countryName: 'Afghanistan',
    dialCode: '+93',
    isO3: 'AFG',
    isO2: 'AF',
    untermEnglish: 'the Islamic Republic of Afghanistan',
    id: '2',
    contactNoLength: '20',
  },
  {
    countryName: 'Albania',
    dialCode: '+355',
    isO3: 'ALB',
    isO2: 'AL',
    untermEnglish: 'the Republic of Albania',
    id: '3',
    contactNoLength: '15',
  },
  {
    countryName: 'Algeria',
    dialCode: '+213',
    isO3: 'DZA',
    isO2: 'DZ',
    untermEnglish: "the People's Democratic Republic of Algeria",
    id: '4',
    contactNoLength: '10',
  },
  {
    countryName: 'American Samoa',
    dialCode: '+1-684',
    isO3: 'ASM',
    isO2: 'AS',
    untermEnglish: '',
    id: '5',
    contactNoLength: '10',
  },
  {
    countryName: 'Andorra',
    dialCode: '+376',
    isO3: 'AND',
    isO2: 'AD',
    untermEnglish: 'the Principality of Andorra',
    id: '6',
    contactNoLength: '10',
  },
  {
    countryName: 'Angola',
    dialCode: '+244',
    isO3: 'AGO',
    isO2: 'AO',
    untermEnglish: 'the Republic of Angola',
    id: '7',
    contactNoLength: '10',
  },
  {
    countryName: 'Anguilla',
    dialCode: '+1-264',
    isO3: 'AIA',
    isO2: 'AI',
    untermEnglish: '',
    id: '8',
    contactNoLength: '10',
  },
  {
    countryName: 'Antigua & Barbuda',
    dialCode: '+1-268',
    isO3: 'ATG',
    isO2: 'AG',
    untermEnglish: 'Antigua and Barbuda',
    id: '10',
    contactNoLength: '10',
  },
  {
    countryName: 'Argentina',
    dialCode: '+54',
    isO3: 'ARG',
    isO2: 'AR',
    untermEnglish: 'the Argentine Republic',
    id: '11',
    contactNoLength: '10',
  },
  {
    countryName: 'Armenia',
    dialCode: '+374',
    isO3: 'ARM',
    isO2: 'AM',
    untermEnglish: 'the Republic of Armenia',
    id: '12',
    contactNoLength: '10',
  },
  {
    countryName: 'Aruba',
    dialCode: '+297',
    isO3: 'ABW',
    isO2: 'AW',
    untermEnglish: '',
    id: '13',
    contactNoLength: '10',
  },
  {
    countryName: 'Australia',
    dialCode: '+61',
    isO3: 'AUS',
    isO2: 'AU',
    untermEnglish: 'Australia',
    id: '14',
    contactNoLength: '10',
  },
  {
    countryName: 'Austria',
    dialCode: '+43',
    isO3: 'AUT',
    isO2: 'AT',
    untermEnglish: 'the Republic of Austria',
    id: '15',
    contactNoLength: '13',
  },
  {
    countryName: 'Azerbaijan',
    dialCode: '+994',
    isO3: 'AZE',
    isO2: 'AZ',
    untermEnglish: 'the Republic of Azerbaijan',
    id: '16',
    contactNoLength: '10',
  },
  {
    countryName: 'Bahamas',
    dialCode: '+1-242',
    isO3: 'BHS',
    isO2: 'BS',
    untermEnglish: 'the Commonwealth of the Bahamas',
    id: '17',
    contactNoLength: '10',
  },
  {
    countryName: 'Bahrain',
    dialCode: '+973',
    isO3: 'BHR',
    isO2: 'BH',
    untermEnglish: 'the Kingdom of Bahrain',
    id: '18',
    contactNoLength: '10',
  },
  {
    countryName: 'Bangladesh',
    dialCode: '+880',
    isO3: 'BGD',
    isO2: 'BD',
    untermEnglish: "the People's Republic of Bangladesh",
    id: '19',
    contactNoLength: '10',
  },
  {
    countryName: 'Barbados',
    dialCode: '+1-246',
    isO3: 'BRB',
    isO2: 'BB',
    untermEnglish: 'Barbados',
    id: '20',
    contactNoLength: '10',
  },
  {
    countryName: 'Belarus',
    dialCode: '+375',
    isO3: 'BLR',
    isO2: 'BY',
    untermEnglish: 'the Republic of Belarus',
    id: '21',
    contactNoLength: '10',
  },
  {
    countryName: 'Belgium',
    dialCode: '+32',
    isO3: 'BEL',
    isO2: 'BE',
    untermEnglish: 'the Kingdom of Belgium',
    id: '22',
    contactNoLength: '10',
  },
  {
    countryName: 'Belize',
    dialCode: '+501',
    isO3: 'BLZ',
    isO2: 'BZ',
    untermEnglish: 'Belize',
    id: '23',
    contactNoLength: '10',
  },
  {
    countryName: 'Benin',
    dialCode: '+229',
    isO3: 'BEN',
    isO2: 'BJ',
    untermEnglish: 'the Republic of Benin',
    id: '24',
    contactNoLength: '10',
  },
  {
    countryName: 'Bermuda',
    dialCode: '+1-441',
    isO3: 'BMU',
    isO2: 'BM',
    untermEnglish: '',
    id: '25',
    contactNoLength: '10',
  },
  {
    countryName: 'Bhutan',
    dialCode: '+975',
    isO3: 'BTN',
    isO2: 'BT',
    untermEnglish: 'the Kingdom of Bhutan',
    id: '26',
    contactNoLength: '10',
  },
  {
    countryName: 'Bolivia',
    dialCode: '+591',
    isO3: 'BOL',
    isO2: 'BO',
    untermEnglish: 'the Plurinational State of Bolivia',
    id: '27',
    contactNoLength: '10',
  },
  {
    countryName: 'Bosnia',
    dialCode: '+387',
    isO3: 'BIH',
    isO2: 'BA',
    untermEnglish: 'Bosnia and Herzegovina',
    id: '29',
    contactNoLength: '10',
  },
  {
    countryName: 'Botswana',
    dialCode: '+267',
    isO3: 'BWA',
    isO2: 'BW',
    untermEnglish: 'the Republic of Botswana',
    id: '30',
    contactNoLength: '10',
  },
  // {
  //   countryName: 'Bouvet Island',
  //   dialCode: '+47',
  //   isO3: 'BVT',
  //   isO2: 'BV',
  //   untermEnglish: '',
  //   id: '31',
  //   contactNoLength: '10',
  // },
  {
    countryName: 'Brazil',
    dialCode: '+55',
    isO3: 'BRA',
    isO2: 'BR',
    untermEnglish: 'the Federative Republic of Brazil',
    id: '32',
    contactNoLength: '10',
  },
  {
    countryName: 'British Indian Ocean Territory',
    dialCode: '+246',
    isO3: 'IOT',
    isO2: 'IO',
    untermEnglish: '',
    id: '33',
    contactNoLength: '10',
  },
  {
    countryName: 'British Virgin Islands',
    dialCode: '+1-284',
    isO3: 'VGB',
    isO2: 'VG',
    untermEnglish: '',
    id: '34',
    contactNoLength: '10',
  },
  {
    countryName: 'Brunei',
    dialCode: '+673',
    isO3: 'BRN',
    isO2: 'BN',
    untermEnglish: 'Brunei Darussalam',
    id: '35',
    contactNoLength: '10',
  },
  {
    countryName: 'Bulgaria',
    dialCode: '+359',
    isO3: 'BGR',
    isO2: 'BG',
    untermEnglish: 'the Republic of Bulgaria',
    id: '36',
    contactNoLength: '10',
  },
  {
    countryName: 'Burkina Faso',
    dialCode: '+226',
    isO3: 'BFA',
    isO2: 'BF',
    untermEnglish: 'Burkina Faso',
    id: '37',
    contactNoLength: '10',
  },
  {
    countryName: 'Burundi',
    dialCode: '+257',
    isO3: 'BDI',
    isO2: 'BI',
    untermEnglish: 'the Republic of Burundi',
    id: '38',
    contactNoLength: '10',
  },
  {
    countryName: 'Cambodia',
    dialCode: '+855',
    isO3: 'KHM',
    isO2: 'KH',
    untermEnglish: 'the Kingdom of Cambodia',
    id: '40',
    contactNoLength: '10',
  },
  {
    countryName: 'Cameroon',
    dialCode: '+237',
    isO3: 'CMR',
    isO2: 'CM',
    untermEnglish: 'the Republic of Cameroon',
    id: '41',
    contactNoLength: '10',
  },
  {
    countryName: 'Canada',
    dialCode: '+1',
    isO3: 'CAN',
    isO2: 'CA',
    untermEnglish: 'Canada',
    id: '42',
    contactNoLength: '10',
  },
  {
    countryName: 'Cape Verde',
    dialCode: '+238',
    isO3: 'CPV',
    isO2: 'CV',
    untermEnglish: 'the Republic of Cabo Verde',
    id: '39',
    contactNoLength: '10',
  },
  {
    countryName: 'Caribbean Netherlands',
    dialCode: '+599',
    isO3: 'BES',
    isO2: 'BQ',
    untermEnglish: '',
    id: '28',
    contactNoLength: '10',
  },
  {
    countryName: 'Cayman Islands',
    dialCode: '+1-345',
    isO3: 'CYM',
    isO2: 'KY',
    untermEnglish: '',
    id: '43',
    contactNoLength: '10',
  },
  {
    countryName: 'Central African Republic',
    dialCode: '+236',
    isO3: 'CAF',
    isO2: 'CF',
    untermEnglish: 'the Central African Republic',
    id: '44',
    contactNoLength: '10',
  },
  {
    countryName: 'Chad',
    dialCode: '+235',
    isO3: 'TCD',
    isO2: 'TD',
    untermEnglish: 'the Republic of Chad',
    id: '45',
    contactNoLength: '10',
  },
  {
    countryName: 'Chile',
    dialCode: '+56',
    isO3: 'CHL',
    isO2: 'CL',
    untermEnglish: 'the Republic of Chile',
    id: '46',
    contactNoLength: '10',
  },
  {
    countryName: 'China',
    dialCode: '+86',
    isO3: 'CHN',
    isO2: 'CN',
    untermEnglish: "the People's Republic of China",
    id: '47',
    contactNoLength: '10',
  },
  {
    countryName: 'Christmas Island',
    dialCode: '+61',
    isO3: 'CXR',
    isO2: 'CX',
    untermEnglish: '',
    id: '50',
    contactNoLength: '10',
  },
  {
    countryName: 'Cocos (Keeling) Islands',
    dialCode: '+61',
    isO3: 'CCK',
    isO2: 'CC',
    untermEnglish: '',
    id: '51',
    contactNoLength: '10',
  },
  {
    countryName: 'Colombia',
    dialCode: '+57',
    isO3: 'COL',
    isO2: 'CO',
    untermEnglish: 'the Republic of Colombia',
    id: '52',
    contactNoLength: '10',
  },
  {
    countryName: 'Comoros',
    dialCode: '+269',
    isO3: 'COM',
    isO2: 'KM',
    untermEnglish: 'the Union of the Comoros',
    id: '53',
    contactNoLength: '10',
  },
  {
    countryName: 'Congo - Brazzaville',
    dialCode: '+242',
    isO3: 'COG',
    isO2: 'CG',
    untermEnglish: 'the Republic of the Congo',
    id: '54',
    contactNoLength: '10',
  },
  {
    countryName: 'Congo - Kinshasa',
    dialCode: '+243',
    isO3: 'COD',
    isO2: 'CD',
    untermEnglish: 'the Democratic Republic of the Congo',
    id: '64',
    contactNoLength: '10',
  },
  {
    countryName: 'Cook Islands',
    dialCode: '+682',
    isO3: 'COK',
    isO2: 'CK',
    untermEnglish: 'the Cook Islands',
    id: '55',
    contactNoLength: '10',
  },
  {
    countryName: 'Costa Rica',
    dialCode: '+506',
    isO3: 'CRI',
    isO2: 'CR',
    untermEnglish: 'the Republic of Costa Rica',
    id: '56',
    contactNoLength: '10',
  },
  {
    countryName: 'Côte d’Ivoire',
    dialCode: '+225',
    isO3: 'CIV',
    isO2: 'CI',
    untermEnglish: "the Republic of Côte d'Ivoire",
    id: '62',
    contactNoLength: '10',
  },
  {
    countryName: 'Croatia',
    dialCode: '+385',
    isO3: 'HRV',
    isO2: 'HR',
    untermEnglish: 'the Republic of Croatia',
    id: '57',
    contactNoLength: '10',
  },
  {
    countryName: 'Cuba',
    dialCode: '+53',
    isO3: 'CUB',
    isO2: 'CU',
    untermEnglish: 'the Republic of Cuba',
    id: '58',
    contactNoLength: '10',
  },
  {
    countryName: 'Curaçao',
    dialCode: '+599',
    isO3: 'CUW',
    isO2: 'CW',
    untermEnglish: '',
    id: '59',
    contactNoLength: '10',
  },
  {
    countryName: 'Cyprus',
    dialCode: '+357',
    isO3: 'CYP',
    isO2: 'CY',
    untermEnglish: 'the Republic of Cyprus',
    id: '60',
    contactNoLength: '10',
  },
  {
    countryName: 'Czechia',
    dialCode: '+420',
    isO3: 'CZE',
    isO2: 'CZ',
    untermEnglish: 'the Czech Republic',
    id: '61',
    contactNoLength: '10',
  },
  {
    countryName: 'Denmark',
    dialCode: '+45',
    isO3: 'DNK',
    isO2: 'DK',
    untermEnglish: 'the Kingdom of Denmark',
    id: '65',
    contactNoLength: '10',
  },
  {
    countryName: 'Djibouti',
    dialCode: '+253',
    isO3: 'DJI',
    isO2: 'DJ',
    untermEnglish: 'the Republic of Djibouti',
    id: '66',
    contactNoLength: '10',
  },
  {
    countryName: 'Dominica',
    dialCode: '+1-767',
    isO3: 'DMA',
    isO2: 'DM',
    untermEnglish: 'the Commonwealth of Dominica',
    id: '67',
    contactNoLength: '10',
  },
  {
    countryName: 'Dominican Republic',
    dialCode: '+1-809',
    isO3: 'DOM',
    isO2: 'DO',
    untermEnglish: 'the Dominican Republic',
    id: '68',
    contactNoLength: '10',
  },
  {
    countryName: 'Ecuador',
    dialCode: '+593',
    isO3: 'ECU',
    isO2: 'EC',
    untermEnglish: 'the Republic of Ecuador',
    id: '69',
    contactNoLength: '10',
  },
  {
    countryName: 'Egypt',
    dialCode: '+20',
    isO3: 'EGY',
    isO2: 'EG',
    untermEnglish: 'the Arab Republic of Egypt',
    id: '70',
    contactNoLength: '10',
  },
  {
    countryName: 'El Salvador',
    dialCode: '+503',
    isO3: 'SLV',
    isO2: 'SV',
    untermEnglish: 'the Republic of El Salvador',
    id: '71',
    contactNoLength: '10',
  },
  {
    countryName: 'Equatorial Guinea',
    dialCode: '+240',
    isO3: 'GNQ',
    isO2: 'GQ',
    untermEnglish: 'the Republic of Equatorial Guinea',
    id: '72',
    contactNoLength: '10',
  },
  {
    countryName: 'Eritrea',
    dialCode: '+291',
    isO3: 'ERI',
    isO2: 'ER',
    untermEnglish: 'the State of Eritrea',
    id: '73',
    contactNoLength: '10',
  },
  {
    countryName: 'Estonia',
    dialCode: '+372',
    isO3: 'EST',
    isO2: 'EE',
    untermEnglish: 'the Republic of Estonia',
    id: '74',
    contactNoLength: '10',
  },
  {
    countryName: 'Eswatini',
    dialCode: '+268',
    isO3: 'SWZ',
    isO2: 'SZ',
    untermEnglish: '',
    id: '75',
    contactNoLength: '10',
  },
  {
    countryName: 'Ethiopia',
    dialCode: '+251',
    isO3: 'ETH',
    isO2: 'ET',
    untermEnglish: 'the Federal Democratic Republic of Ethiopia',
    id: '76',
    contactNoLength: '10',
  },
  {
    countryName: 'Falkland Islands',
    dialCode: '+500',
    isO3: 'FLK',
    isO2: 'FK',
    untermEnglish: '',
    id: '77',
    contactNoLength: '10',
  },
  {
    countryName: 'Faroe Islands',
    dialCode: '+298',
    isO3: 'FRO',
    isO2: 'FO',
    untermEnglish: '',
    id: '78',
    contactNoLength: '10',
  },
  {
    countryName: 'Fiji',
    dialCode: '+679',
    isO3: 'FJI',
    isO2: 'FJ',
    untermEnglish: 'the Republic of Fiji',
    id: '79',
    contactNoLength: '10',
  },
  {
    countryName: 'Finland',
    dialCode: '+358',
    isO3: 'FIN',
    isO2: 'FI',
    untermEnglish: 'the Republic of Finland',
    id: '80',
    contactNoLength: '10',
  },
  {
    countryName: 'France',
    dialCode: '+33',
    isO3: 'FRA',
    isO2: 'FR',
    untermEnglish: 'the French Republic',
    id: '81',
    contactNoLength: '10',
  },
  {
    countryName: 'French Guiana',
    dialCode: '+594',
    isO3: 'GUF',
    isO2: 'GF',
    untermEnglish: '',
    id: '82',
    contactNoLength: '10',
  },
  {
    countryName: 'French Polynesia',
    dialCode: '+689',
    isO3: 'PYF',
    isO2: 'PF',
    untermEnglish: '',
    id: '83',
    contactNoLength: '10',
  },
  // {
  //   countryName: 'French Southern Territories',
  //   dialCode: '+262',
  //   isO3: 'ATF',
  //   isO2: 'TF',
  //   untermEnglish: '',
  //   id: '84',
  //   contactNoLength: '10',
  // },
  {
    countryName: 'Gabon',
    dialCode: '+241',
    isO3: 'GAB',
    isO2: 'GA',
    untermEnglish: 'the Gabonese Republic',
    id: '85',
    contactNoLength: '10',
  },
  {
    countryName: 'Gambia',
    dialCode: '+220',
    isO3: 'GMB',
    isO2: 'GM',
    untermEnglish: 'the Republic of the Gambia',
    id: '86',
    contactNoLength: '10',
  },
  {
    countryName: 'Georgia',
    dialCode: '+995',
    isO3: 'GEO',
    isO2: 'GE',
    untermEnglish: 'Georgia',
    id: '87',
    contactNoLength: '10',
  },
  {
    countryName: 'Germany',
    dialCode: '+49',
    isO3: 'DEU',
    isO2: 'DE',
    untermEnglish: 'the Federal Republic of Germany',
    id: '88',
    contactNoLength: '10',
  },
  {
    countryName: 'Ghana',
    dialCode: '+233',
    isO3: 'GHA',
    isO2: 'GH',
    untermEnglish: 'the Republic of Ghana',
    id: '89',
    contactNoLength: '10',
  },
  {
    countryName: 'Gibraltar',
    dialCode: '+350',
    isO3: 'GIB',
    isO2: 'GI',
    untermEnglish: '',
    id: '90',
    contactNoLength: '10',
  },
  {
    countryName: 'Greece',
    dialCode: '+30',
    isO3: 'GRC',
    isO2: 'GR',
    untermEnglish: 'the Hellenic Republic',
    id: '91',
    contactNoLength: '10',
  },
  {
    countryName: 'Greenland',
    dialCode: '+299',
    isO3: 'GRL',
    isO2: 'GL',
    untermEnglish: '',
    id: '92',
    contactNoLength: '10',
  },
  {
    countryName: 'Grenada',
    dialCode: '+1-473',
    isO3: 'GRD',
    isO2: 'GD',
    untermEnglish: 'Grenada',
    id: '93',
    contactNoLength: '10',
  },
  {
    countryName: 'Guadeloupe',
    dialCode: '+590',
    isO3: 'GLP',
    isO2: 'GP',
    untermEnglish: '',
    id: '94',
    contactNoLength: '10',
  },
  {
    countryName: 'Guam',
    dialCode: '+1-671',
    isO3: 'GUM',
    isO2: 'GU',
    untermEnglish: '',
    id: '95',
    contactNoLength: '10',
  },
  {
    countryName: 'Guatemala',
    dialCode: '+502',
    isO3: 'GTM',
    isO2: 'GT',
    untermEnglish: 'the Republic of Guatemala',
    id: '96',
    contactNoLength: '10',
  },
  {
    countryName: 'Guernsey',
    dialCode: '+44',
    isO3: 'GGY',
    isO2: 'GG',
    untermEnglish: '',
    id: '97',
    contactNoLength: '10',
  },
  {
    countryName: 'Guinea',
    dialCode: '+224',
    isO3: 'GIN',
    isO2: 'GN',
    untermEnglish: 'the Republic of Guinea',
    id: '98',
    contactNoLength: '10',
  },
  {
    countryName: 'Guinea-Bissau',
    dialCode: '+245',
    isO3: 'GNB',
    isO2: 'GW',
    untermEnglish: 'the Republic of Guinea-Bissau',
    id: '99',
    contactNoLength: '10',
  },
  {
    countryName: 'Guyana',
    dialCode: '+592',
    isO3: 'GUY',
    isO2: 'GY',
    untermEnglish: 'the Republic of Guyana',
    id: '100',
    contactNoLength: '10',
  },
  {
    countryName: 'Haiti',
    dialCode: '+509',
    isO3: 'HTI',
    isO2: 'HT',
    untermEnglish: 'the Republic of Haiti',
    id: '101',
    contactNoLength: '10',
  },
  // {
  //   countryName: 'Heard & McDonald Islands',
  //   dialCode: '+672',
  //   isO3: 'HMD',
  //   isO2: 'HM',
  //   untermEnglish: '',
  //   id: '102',
  //   contactNoLength: '10',
  // },
  {
    countryName: 'Honduras',
    dialCode: '+504',
    isO3: 'HND',
    isO2: 'HN',
    untermEnglish: 'the Republic of Honduras',
    id: '104',
    contactNoLength: '10',
  },
  {
    countryName: 'Hong Kong',
    dialCode: '+852',
    isO3: 'HKG',
    isO2: 'HK',
    untermEnglish: '',
    id: '48',
    contactNoLength: '10',
  },
  {
    countryName: 'Hungary',
    dialCode: '+36',
    isO3: 'HUN',
    isO2: 'HU',
    untermEnglish: 'Hungary',
    id: '105',
    contactNoLength: '10',
  },
  {
    countryName: 'Iceland',
    dialCode: '+354',
    isO3: 'ISL',
    isO2: 'IS',
    untermEnglish: 'the Republic of Iceland',
    id: '106',
    contactNoLength: '10',
  },
  {
    countryName: 'Indonesia',
    dialCode: '+62',
    isO3: 'IDN',
    isO2: 'ID',
    untermEnglish: 'the Republic of Indonesia',
    id: '108',
    contactNoLength: '10',
  },
  {
    countryName: 'Iran',
    dialCode: '+98',
    isO3: 'IRN',
    isO2: 'IR',
    untermEnglish: 'the Islamic Republic of Iran',
    id: '109',
    contactNoLength: '10',
  },
  {
    countryName: 'Iraq',
    dialCode: '+964',
    isO3: 'IRQ',
    isO2: 'IQ',
    untermEnglish: 'the Republic of Iraq',
    id: '110',
    contactNoLength: '10',
  },
  {
    countryName: 'Ireland',
    dialCode: '+353',
    isO3: 'IRL',
    isO2: 'IE',
    untermEnglish: 'Ireland',
    id: '111',
    contactNoLength: '10',
  },
  {
    countryName: 'Isle of Man',
    dialCode: '+44',
    isO3: 'IMN',
    isO2: 'IM',
    untermEnglish: '',
    id: '112',
    contactNoLength: '10',
  },
  {
    countryName: 'Israel',
    dialCode: '+972',
    isO3: 'ISR',
    isO2: 'IL',
    untermEnglish: 'the State of Israel',
    id: '113',
    contactNoLength: '10',
  },
  {
    countryName: 'Italy',
    dialCode: '+39',
    isO3: 'ITA',
    isO2: 'IT',
    untermEnglish: 'the Republic of Italy',
    id: '114',
    contactNoLength: '10',
  },
  {
    countryName: 'Jamaica',
    dialCode: '+1-876',
    isO3: 'JAM',
    isO2: 'JM',
    untermEnglish: 'Jamaica',
    id: '115',
    contactNoLength: '10',
  },
  {
    countryName: 'Japan',
    dialCode: '+81',
    isO3: 'JPN',
    isO2: 'JP',
    untermEnglish: 'Japan',
    id: '116',
    contactNoLength: '10',
  },
  {
    countryName: 'Jersey',
    dialCode: '+44',
    isO3: 'JEY',
    isO2: 'JE',
    untermEnglish: '',
    id: '117',
    contactNoLength: '10',
  },
  {
    countryName: 'Jordan',
    dialCode: '+962',
    isO3: 'JOR',
    isO2: 'JO',
    untermEnglish: 'the Hashemite Kingdom of Jordan',
    id: '118',
    contactNoLength: '10',
  },
  {
    countryName: 'Kazakhstan',
    dialCode: '+7',
    isO3: 'KAZ',
    isO2: 'KZ',
    untermEnglish: 'the Republic of Kazakhstan',
    id: '119',
    contactNoLength: '10',
  },
  {
    countryName: 'Kenya',
    dialCode: '+254',
    isO3: 'KEN',
    isO2: 'KE',
    untermEnglish: 'the Republic of Kenya',
    id: '120',
    contactNoLength: '10',
  },
  {
    countryName: 'Kiribati',
    dialCode: '+686',
    isO3: 'KIR',
    isO2: 'KI',
    untermEnglish: 'the Republic of Kiribati',
    id: '121',
    contactNoLength: '10',
  },
  {
    countryName: 'Kuwait',
    dialCode: '+965',
    isO3: 'KWT',
    isO2: 'KW',
    untermEnglish: 'the State of Kuwait',
    id: '122',
    contactNoLength: '10',
  },
  {
    countryName: 'Kyrgyzstan',
    dialCode: '+996',
    isO3: 'KGZ',
    isO2: 'KG',
    untermEnglish: 'the Kyrgyz Republic',
    id: '123',
    contactNoLength: '10',
  },
  {
    countryName: 'Laos',
    dialCode: '+856',
    isO3: 'LAO',
    isO2: 'LA',
    untermEnglish: "the Lao People's Democratic Republic",
    id: '124',
    contactNoLength: '10',
  },
  {
    countryName: 'Latvia',
    dialCode: '+371',
    isO3: 'LVA',
    isO2: 'LV',
    untermEnglish: 'the Republic of Latvia',
    id: '125',
    contactNoLength: '10',
  },
  {
    countryName: 'Lebanon',
    dialCode: '+961',
    isO3: 'LBN',
    isO2: 'LB',
    untermEnglish: 'the Lebanese Republic',
    id: '126',
    contactNoLength: '10',
  },
  {
    countryName: 'Lesotho',
    dialCode: '+266',
    isO3: 'LSO',
    isO2: 'LS',
    untermEnglish: 'the Kingdom of Lesotho',
    id: '127',
    contactNoLength: '10',
  },
  {
    countryName: 'Liberia',
    dialCode: '+231',
    isO3: 'LBR',
    isO2: 'LR',
    untermEnglish: 'the Republic of Liberia',
    id: '128',
    contactNoLength: '10',
  },
  {
    countryName: 'Libya',
    dialCode: '+218',
    isO3: 'LBY',
    isO2: 'LY',
    untermEnglish: 'Libya',
    id: '129',
    contactNoLength: '10',
  },
  {
    countryName: 'Liechtenstein',
    dialCode: '+423',
    isO3: 'LIE',
    isO2: 'LI',
    untermEnglish: 'the Principality of Liechtenstein',
    id: '130',
    contactNoLength: '10',
  },
  {
    countryName: 'Lithuania',
    dialCode: '+370',
    isO3: 'LTU',
    isO2: 'LT',
    untermEnglish: 'the Republic of Lithuania',
    id: '131',
    contactNoLength: '10',
  },
  {
    countryName: 'Luxembourg',
    dialCode: '+352',
    isO3: 'LUX',
    isO2: 'LU',
    untermEnglish: 'the Grand Duchy of Luxembourg',
    id: '132',
    contactNoLength: '10',
  },
  {
    countryName: 'Macau',
    dialCode: '+853',
    isO3: 'MAC',
    isO2: 'MO',
    untermEnglish: '',
    id: '49',
    contactNoLength: '10',
  },
  {
    countryName: 'Macedonia',
    dialCode: '+389',
    isO3: 'MKD',
    isO2: 'MK',
    untermEnglish: 'the former Yugoslav Republic of Macedonia',
    id: '133',
    contactNoLength: '10',
  },
  {
    countryName: 'Madagascar',
    dialCode: '+261',
    isO3: 'MDG',
    isO2: 'MG',
    untermEnglish: 'the Republic of Madagascar',
    id: '134',
    contactNoLength: '10',
  },
  {
    countryName: 'Malawi',
    dialCode: '+265',
    isO3: 'MWI',
    isO2: 'MW',
    untermEnglish: 'the Republic of Malawi',
    id: '135',
    contactNoLength: '10',
  },
  {
    countryName: 'Malaysia',
    dialCode: '+60',
    isO3: 'MYS',
    isO2: 'MY',
    untermEnglish: 'Malaysia',
    id: '136',
    contactNoLength: '10',
  },
  {
    countryName: 'Maldives',
    dialCode: '+960',
    isO3: 'MDV',
    isO2: 'MV',
    untermEnglish: 'the Republic of Maldives',
    id: '137',
    contactNoLength: '10',
  },
  {
    countryName: 'Mali',
    dialCode: '+223',
    isO3: 'MLI',
    isO2: 'ML',
    untermEnglish: 'the Republic of Mali',
    id: '138',
    contactNoLength: '10',
  },
  {
    countryName: 'Malta',
    dialCode: '+356',
    isO3: 'MLT',
    isO2: 'MT',
    untermEnglish: 'the Republic of Malta',
    id: '139',
    contactNoLength: '10',
  },
  {
    countryName: 'Marshall Islands',
    dialCode: '+692',
    isO3: 'MHL',
    isO2: 'MH',
    untermEnglish: 'the Republic of the Marshall Islands',
    id: '140',
    contactNoLength: '10',
  },
  {
    countryName: 'Martinique',
    dialCode: '+596',
    isO3: 'MTQ',
    isO2: 'MQ',
    untermEnglish: '',
    id: '141',
    contactNoLength: '10',
  },
  {
    countryName: 'Mauritania',
    dialCode: '+222',
    isO3: 'MRT',
    isO2: 'MR',
    untermEnglish: 'the Islamic Republic of Mauritania',
    id: '142',
    contactNoLength: '10',
  },
  {
    countryName: 'Mauritius',
    dialCode: '+230',
    isO3: 'MUS',
    isO2: 'MU',
    untermEnglish: 'the Republic of Mauritius',
    id: '143',
    contactNoLength: '10',
  },
  {
    countryName: 'Mayotte',
    dialCode: '+262',
    isO3: 'MYT',
    isO2: 'YT',
    untermEnglish: '',
    id: '144',
    contactNoLength: '10',
  },
  {
    countryName: 'Mexico',
    dialCode: '+52',
    isO3: 'MEX',
    isO2: 'MX',
    untermEnglish: 'the United Mexican States',
    id: '145',
    contactNoLength: '10',
  },
  {
    countryName: 'Micronesia',
    dialCode: '+691',
    isO3: 'FSM',
    isO2: 'FM',
    untermEnglish: 'the Federated States of Micronesia',
    id: '146',
    contactNoLength: '10',
  },
  {
    countryName: 'Moldova',
    dialCode: '+373',
    isO3: 'MDA',
    isO2: 'MD',
    untermEnglish: 'the Republic of Moldova',
    id: '181',
    contactNoLength: '10',
  },
  {
    countryName: 'Monaco',
    dialCode: '+377',
    isO3: 'MCO',
    isO2: 'MC',
    untermEnglish: 'the Principality of Monaco',
    id: '147',
    contactNoLength: '10',
  },
  {
    countryName: 'Mongolia',
    dialCode: '+976',
    isO3: 'MNG',
    isO2: 'MN',
    untermEnglish: 'Mongolia',
    id: '148',
    contactNoLength: '10',
  },
  {
    countryName: 'Montenegro',
    dialCode: '+382',
    isO3: 'MNE',
    isO2: 'ME',
    untermEnglish: 'Montenegro',
    id: '149',
    contactNoLength: '10',
  },
  {
    countryName: 'Montserrat',
    dialCode: '+1-664',
    isO3: 'MSR',
    isO2: 'MS',
    untermEnglish: '',
    id: '150',
    contactNoLength: '10',
  },
  {
    countryName: 'Morocco',
    dialCode: '+212',
    isO3: 'MAR',
    isO2: 'MA',
    untermEnglish: 'the Kingdom of Morocco',
    id: '151',
    contactNoLength: '10',
  },
  {
    countryName: 'Mozambique',
    dialCode: '+258',
    isO3: 'MOZ',
    isO2: 'MZ',
    untermEnglish: 'the Republic of Mozambique',
    id: '152',
    contactNoLength: '10',
  },
  {
    countryName: 'Myanmar',
    dialCode: '+95',
    isO3: 'MMR',
    isO2: 'MM',
    untermEnglish: 'the Republic of the Union of Myanmar',
    id: '153',
    contactNoLength: '10',
  },
  {
    countryName: 'Namibia',
    dialCode: '+264',
    isO3: 'NAM',
    isO2: 'NA',
    untermEnglish: 'the Republic of Namibia',
    id: '154',
    contactNoLength: '10',
  },
  {
    countryName: 'Nauru',
    dialCode: '+674',
    isO3: 'NRU',
    isO2: 'NR',
    untermEnglish: 'the Republic of Nauru',
    id: '155',
    contactNoLength: '10',
  },
  {
    countryName: 'Nepal',
    dialCode: '+977',
    isO3: 'NPL',
    isO2: 'NP',
    untermEnglish: 'the Federal Democratic Republic of Nepal',
    id: '156',
    contactNoLength: '10',
  },
  {
    countryName: 'Netherlands',
    dialCode: '+31',
    isO3: 'NLD',
    isO2: 'NL',
    untermEnglish: 'the Kingdom of the Netherlands',
    id: '157',
    contactNoLength: '10',
  },
  {
    countryName: 'New Caledonia',
    dialCode: '+687',
    isO3: 'NCL',
    isO2: 'NC',
    untermEnglish: '',
    id: '158',
    contactNoLength: '10',
  },
  {
    countryName: 'New Zealand',
    dialCode: '+64',
    isO3: 'NZL',
    isO2: 'NZ',
    untermEnglish: 'New Zealand',
    id: '159',
    contactNoLength: '10',
  },
  {
    countryName: 'Nicaragua',
    dialCode: '+505',
    isO3: 'NIC',
    isO2: 'NI',
    untermEnglish: 'the Republic of Nicaragua',
    id: '160',
    contactNoLength: '10',
  },
  {
    countryName: 'Niger',
    dialCode: '+227',
    isO3: 'NER',
    isO2: 'NE',
    untermEnglish: 'the Republic of the Niger',
    id: '161',
    contactNoLength: '10',
  },
  {
    countryName: 'Nigeria',
    dialCode: '+234',
    isO3: 'NGA',
    isO2: 'NG',
    untermEnglish: 'the Federal Republic of Nigeria',
    id: '162',
    contactNoLength: '10',
  },
  {
    countryName: 'Niue',
    dialCode: '+683',
    isO3: 'NIU',
    isO2: 'NU',
    untermEnglish: 'Niue',
    id: '163',
    contactNoLength: '10',
  },
  {
    countryName: 'Norfolk Island',
    dialCode: '+672',
    isO3: 'NFK',
    isO2: 'NF',
    untermEnglish: '',
    id: '164',
    contactNoLength: '10',
  },
  {
    countryName: 'North Korea',
    dialCode: '+850',
    isO3: 'PRK',
    isO2: 'KP',
    untermEnglish: "the Democratic People's Republic of Korea",
    id: '63',
    contactNoLength: '10',
  },
  {
    countryName: 'Northern Mariana Islands',
    dialCode: '+1-670',
    isO3: 'MNP',
    isO2: 'MP',
    untermEnglish: '',
    id: '165',
    contactNoLength: '10',
  },
  {
    countryName: 'Norway',
    dialCode: '+47',
    isO3: 'NOR',
    isO2: 'NO',
    untermEnglish: 'the Kingdom of Norway',
    id: '166',
    contactNoLength: '10',
  },
  {
    countryName: 'Oman',
    dialCode: '+968',
    isO3: 'OMN',
    isO2: 'OM',
    untermEnglish: 'the Sultanate of Oman',
    id: '167',
    contactNoLength: '10',
  },
  {
    countryName: 'Pakistan',
    dialCode: '+92',
    isO3: 'PAK',
    isO2: 'PK',
    untermEnglish: 'the Islamic Republic of Pakistan',
    id: '168',
    contactNoLength: '10',
  },
  {
    countryName: 'Palau',
    dialCode: '+680',
    isO3: 'PLW',
    isO2: 'PW',
    untermEnglish: 'the Republic of Palau',
    id: '169',
    contactNoLength: '10',
  },
  {
    countryName: 'Palestine',
    dialCode: '+970',
    isO3: 'PSE',
    isO2: 'PS',
    untermEnglish: 'State of Palestine',
    id: '212',
    contactNoLength: '10',
  },
  {
    countryName: 'Panama',
    dialCode: '+507',
    isO3: 'PAN',
    isO2: 'PA',
    untermEnglish: 'the Republic of Panama',
    id: '170',
    contactNoLength: '10',
  },
  {
    countryName: 'Papua New Guinea',
    dialCode: '+675',
    isO3: 'PNG',
    isO2: 'PG',
    untermEnglish: 'Independent State of Papua New Guinea',
    id: '171',
    contactNoLength: '10',
  },
  {
    countryName: 'Paraguay',
    dialCode: '+595',
    isO3: 'PRY',
    isO2: 'PY',
    untermEnglish: 'the Republic of Paraguay',
    id: '172',
    contactNoLength: '10',
  },
  {
    countryName: 'Peru',
    dialCode: '+51',
    isO3: 'PER',
    isO2: 'PE',
    untermEnglish: 'the Republic of Peru',
    id: '173',
    contactNoLength: '10',
  },
  {
    countryName: 'Philippines',
    dialCode: '+63',
    isO3: 'PHL',
    isO2: 'PH',
    untermEnglish: 'the Republic of the Philippines',
    id: '174',
    contactNoLength: '10',
  },
  // {
  //   countryName: 'Pitcairn Islands',
  //   dialCode: '+870',
  //   isO3: 'PCN',
  //   isO2: 'PN',
  //   untermEnglish: '',
  //   id: '175',
  //   contactNoLength: '10',
  // },
  {
    countryName: 'Poland',
    dialCode: '+48',
    isO3: 'POL',
    isO2: 'PL',
    untermEnglish: 'the Republic of Poland',
    id: '176',
    contactNoLength: '10',
  },
  {
    countryName: 'Portugal',
    dialCode: '+351',
    isO3: 'PRT',
    isO2: 'PT',
    untermEnglish: 'the Portuguese Republic',
    id: '177',
    contactNoLength: '10',
  },
  {
    countryName: 'Puerto Rico',
    dialCode: '+1',
    isO3: 'PRI',
    isO2: 'PR',
    untermEnglish: '',
    id: '178',
    contactNoLength: '10',
  },
  {
    countryName: 'Qatar',
    dialCode: '+974',
    isO3: 'QAT',
    isO2: 'QA',
    untermEnglish: 'the State of Qatar',
    id: '179',
    contactNoLength: '10',
  },
  {
    countryName: 'Réunion',
    dialCode: '+262',
    isO3: 'REU',
    isO2: 'RE',
    untermEnglish: '',
    id: '185',
    contactNoLength: '10',
  },
  {
    countryName: 'Romania',
    dialCode: '+40',
    isO3: 'ROU',
    isO2: 'RO',
    untermEnglish: 'Romania',
    id: '182',
    contactNoLength: '10',
  },
  {
    countryName: 'Russia',
    dialCode: '+7',
    isO3: 'RUS',
    isO2: 'RU',
    untermEnglish: 'the Russian Federation',
    id: '183',
    contactNoLength: '10',
  },
  {
    countryName: 'Rwanda',
    dialCode: '+250',
    isO3: 'RWA',
    isO2: 'RW',
    untermEnglish: 'the Republic of Rwanda',
    id: '184',
    contactNoLength: '10',
  },
  {
    countryName: 'Samoa',
    dialCode: '+685',
    isO3: 'WSM',
    isO2: 'WS',
    untermEnglish: 'the Independent State of Samoa',
    id: '193',
    contactNoLength: '10',
  },
  {
    countryName: 'San Marino',
    dialCode: '+378',
    isO3: 'SMR',
    isO2: 'SM',
    untermEnglish: 'the Republic of San Marino',
    id: '194',
    contactNoLength: '10',
  },
  {
    countryName: 'São Tomé & Príncipe',
    dialCode: '+239',
    isO3: 'STP',
    isO2: 'ST',
    untermEnglish: 'the Democratic Republic of Sao Tome and Principe',
    id: '195',
    contactNoLength: '10',
  },
  {
    countryName: 'Saudi Arabia',
    dialCode: '+966',
    isO3: 'SAU',
    isO2: 'SA',
    untermEnglish: 'the Kingdom of Saudi Arabia',
    id: '196',
    contactNoLength: '10',
  },
  {
    countryName: 'Senegal',
    dialCode: '+221',
    isO3: 'SEN',
    isO2: 'SN',
    untermEnglish: 'the Republic of Senegal',
    id: '197',
    contactNoLength: '10',
  },
  {
    countryName: 'Serbia',
    dialCode: '+381',
    isO3: 'SRB',
    isO2: 'RS',
    untermEnglish: 'the Republic of Serbia',
    id: '198',
    contactNoLength: '10',
  },
  {
    countryName: 'Seychelles',
    dialCode: '+248',
    isO3: 'SYC',
    isO2: 'SC',
    untermEnglish: 'the Republic of Seychelles',
    id: '199',
    contactNoLength: '10',
  },
  {
    countryName: 'Sierra Leone',
    dialCode: '+232',
    isO3: 'SLE',
    isO2: 'SL',
    untermEnglish: 'the Republic of Sierra Leone',
    id: '200',
    contactNoLength: '10',
  },
  {
    countryName: 'Singapore',
    dialCode: '+65',
    isO3: 'SGP',
    isO2: 'SG',
    untermEnglish: 'the Republic of Singapore',
    id: '201',
    contactNoLength: '10',
  },
  {
    countryName: 'Sint Maarten',
    dialCode: '+1-721',
    isO3: 'SXM',
    isO2: 'SX',
    untermEnglish: '',
    id: '202',
    contactNoLength: '10',
  },
  {
    countryName: 'Slovakia',
    dialCode: '+421',
    isO3: 'SVK',
    isO2: 'SK',
    untermEnglish: 'the Slovak Republic',
    id: '203',
    contactNoLength: '10',
  },
  {
    countryName: 'Slovenia',
    dialCode: '+386',
    isO3: 'SVN',
    isO2: 'SI',
    untermEnglish: 'the Republic of Slovenia',
    id: '204',
    contactNoLength: '10',
  },
  {
    countryName: 'Solomon Islands',
    dialCode: '+677',
    isO3: 'SLB',
    isO2: 'SB',
    untermEnglish: 'Solomon Islands',
    id: '205',
    contactNoLength: '10',
  },
  {
    countryName: 'Somalia',
    dialCode: '+252',
    isO3: 'SOM',
    isO2: 'SO',
    untermEnglish: 'the Federal Republic of Somalia',
    id: '206',
    contactNoLength: '10',
  },
  {
    countryName: 'South Africa',
    dialCode: '+27',
    isO3: 'ZAF',
    isO2: 'ZA',
    untermEnglish: 'the Republic of South Africa',
    id: '207',
    contactNoLength: '10',
  },
  // {
  //   countryName: 'South Georgia & South Sandwich Islands',
  //   dialCode: '+500',
  //   isO3: 'SGS',
  //   isO2: 'GS',
  //   untermEnglish: '',
  //   id: '208',
  //   contactNoLength: '10',
  // },
  {
    countryName: 'South Korea',
    dialCode: '+82',
    isO3: 'KOR',
    isO2: 'KR',
    untermEnglish: 'the Republic of Korea',
    id: '180',
    contactNoLength: '10',
  },
  {
    countryName: 'South Sudan',
    dialCode: '+211',
    isO3: 'SSD',
    isO2: 'SS',
    untermEnglish: 'the Republic of South Sudan',
    id: '209',
    contactNoLength: '10',
  },
  {
    countryName: 'Spain',
    dialCode: '+34',
    isO3: 'ESP',
    isO2: 'ES',
    untermEnglish: 'the Kingdom of Spain',
    id: '210',
    contactNoLength: '10',
  },
  {
    countryName: 'Sri Lanka',
    dialCode: '+94',
    isO3: 'LKA',
    isO2: 'LK',
    untermEnglish: 'the Democratic Socialist Republic of Sri Lanka',
    id: '211',
    contactNoLength: '10',
  },
  {
    countryName: 'St. Barthélemy',
    dialCode: '+590',
    isO3: 'BLM',
    isO2: 'BL',
    untermEnglish: '',
    id: '186',
    contactNoLength: '10',
  },
  {
    countryName: 'St. Helena',
    dialCode: '+290',
    isO3: 'SHN',
    isO2: 'SH',
    untermEnglish: '',
    id: '187',
    contactNoLength: '10',
  },
  {
    countryName: 'St. Kitts & Nevis',
    dialCode: '+1-869',
    isO3: 'KNA',
    isO2: 'KN',
    untermEnglish: 'Saint Kitts and Nevis',
    id: '188',
    contactNoLength: '10',
  },
  {
    countryName: 'St. Lucia',
    dialCode: '+1-758',
    isO3: 'LCA',
    isO2: 'LC',
    untermEnglish: 'Saint Lucia',
    id: '189',
    contactNoLength: '10',
  },
  {
    countryName: 'St. Martin',
    dialCode: '+590',
    isO3: 'MAF',
    isO2: 'MF',
    untermEnglish: '',
    id: '190',
    contactNoLength: '10',
  },
  {
    countryName: 'St. Pierre & Miquelon',
    dialCode: '+508',
    isO3: 'SPM',
    isO2: 'PM',
    untermEnglish: '',
    id: '191',
    contactNoLength: '10',
  },
  {
    countryName: 'St. Vincent & Grenadines',
    dialCode: '+1-784',
    isO3: 'VCT',
    isO2: 'VC',
    untermEnglish: 'Saint Vincent and the Grenadines',
    id: '192',
    contactNoLength: '10',
  },
  {
    countryName: 'Sudan',
    dialCode: '+249',
    isO3: 'SDN',
    isO2: 'SD',
    untermEnglish: 'the Republic of the Sudan',
    id: '213',
    contactNoLength: '10',
  },
  {
    countryName: 'Suriname',
    dialCode: '+597',
    isO3: 'SUR',
    isO2: 'SR',
    untermEnglish: 'the Republic of Suriname',
    id: '214',
    contactNoLength: '10',
  },
  {
    countryName: 'Svalbard & Jan Mayen',
    dialCode: '+47',
    isO3: 'SJM',
    isO2: 'SJ',
    untermEnglish: '',
    id: '215',
    contactNoLength: '10',
  },
  {
    countryName: 'Sweden',
    dialCode: '+46',
    isO3: 'SWE',
    isO2: 'SE',
    untermEnglish: 'the Kingdom of Sweden',
    id: '216',
    contactNoLength: '10',
  },
  {
    countryName: 'Switzerland',
    dialCode: '+41',
    isO3: 'CHE',
    isO2: 'CH',
    untermEnglish: 'the Swiss Confederation',
    id: '217',
    contactNoLength: '10',
  },
  {
    countryName: 'Syria',
    dialCode: '+963',
    isO3: 'SYR',
    isO2: 'SY',
    untermEnglish: 'the Syrian Arab Republic',
    id: '218',
    contactNoLength: '10',
  },
  {
    countryName: 'Taiwan',
    dialCode: '+886',
    isO3: 'TWN',
    isO2: 'TW',
    untermEnglish: 'Taiwan',
    id: '219',
    contactNoLength: '10',
  },
  {
    countryName: 'Tajikistan',
    dialCode: '+992',
    isO3: 'TJK',
    isO2: 'TJ',
    untermEnglish: 'the Republic of Tajikistan',
    id: '220',
    contactNoLength: '10',
  },
  {
    countryName: 'Tanzania',
    dialCode: '+255',
    isO3: 'TZA',
    isO2: 'TZ',
    untermEnglish: 'the United Republic of Tanzania',
    id: '221',
    contactNoLength: '10',
  },
  {
    countryName: 'Thailand',
    dialCode: '+66',
    isO3: 'THA',
    isO2: 'TH',
    untermEnglish: 'the Kingdom of Thailand',
    id: '222',
    contactNoLength: '10',
  },
  {
    countryName: 'Timor-Leste',
    dialCode: '+670',
    isO3: 'TLS',
    isO2: 'TL',
    untermEnglish: 'the Democratic Republic of Timor-Leste',
    id: '223',
    contactNoLength: '10',
  },
  {
    countryName: 'Togo',
    dialCode: '+228',
    isO3: 'TGO',
    isO2: 'TG',
    untermEnglish: 'the Togolese Republic',
    id: '224',
    contactNoLength: '10',
  },
  {
    countryName: 'Tokelau',
    dialCode: '+690',
    isO3: 'TKL',
    isO2: 'TK',
    untermEnglish: '',
    id: '225',
    contactNoLength: '10',
  },
  {
    countryName: 'Tonga',
    dialCode: '+676',
    isO3: 'TON',
    isO2: 'TO',
    untermEnglish: 'the Kingdom of Tonga',
    id: '226',
    contactNoLength: '10',
  },
  {
    countryName: 'Trinidad & Tobago',
    dialCode: '+1-868',
    isO3: 'TTO',
    isO2: 'TT',
    untermEnglish: 'the Republic of Trinidad and Tobago',
    id: '227',
    contactNoLength: '10',
  },
  {
    countryName: 'Tunisia',
    dialCode: '+216',
    isO3: 'TUN',
    isO2: 'TN',
    untermEnglish: 'the Republic of Tunisia',
    id: '228',
    contactNoLength: '10',
  },
  {
    countryName: 'Turkey',
    dialCode: '+90',
    isO3: 'TUR',
    isO2: 'TR',
    untermEnglish: 'the Republic of Turkey',
    id: '229',
    contactNoLength: '10',
  },
  {
    countryName: 'Turkmenistan',
    dialCode: '+993',
    isO3: 'TKM',
    isO2: 'TM',
    untermEnglish: 'Turkmenistan',
    id: '230',
    contactNoLength: '10',
  },
  {
    countryName: 'Turks & Caicos Islands',
    dialCode: '+1-649',
    isO3: 'TCA',
    isO2: 'TC',
    untermEnglish: '',
    id: '231',
    contactNoLength: '10',
  },
  {
    countryName: 'Tuvalu',
    dialCode: '+688',
    isO3: 'TUV',
    isO2: 'TV',
    untermEnglish: 'Tuvalu',
    id: '232',
    contactNoLength: '10',
  },
  // {
  //   countryName: 'U.S. Outlying Islands',
  //   dialCode: '+246',
  //   isO3: 'UMI',
  //   isO2: 'UM',
  //   untermEnglish: '',
  //   id: '237',
  //   contactNoLength: '10',
  // },
  {
    countryName: 'U.S. Virgin Islands',
    dialCode: '+1-340',
    isO3: 'VIR',
    isO2: 'VI',
    untermEnglish: '',
    id: '238',
    contactNoLength: '10',
  },
  {
    countryName: 'Uganda',
    dialCode: '+256',
    isO3: 'UGA',
    isO2: 'UG',
    untermEnglish: 'the Republic of Uganda',
    id: '233',
    contactNoLength: '10',
  },
  {
    countryName: 'UK',
    dialCode: '+44',
    isO3: 'GBR',
    isO2: 'GB',
    untermEnglish: 'the United Kingdom of Great Britain and Northern Ireland',
    id: '236',
    contactNoLength: '10',
  },
  {
    countryName: 'Ukraine',
    dialCode: '+380',
    isO3: 'UKR',
    isO2: 'UA',
    untermEnglish: 'Ukraine',
    id: '234',
    contactNoLength: '10',
  },
  {
    countryName: 'United Arab Emirates',
    dialCode: '+971',
    isO3: 'ARE',
    isO2: 'AE',
    untermEnglish: 'the United Arab Emirates',
    id: '235',
    contactNoLength: '10',
  },
  {
    countryName: 'Uruguay',
    dialCode: '+598',
    isO3: 'URY',
    isO2: 'UY',
    untermEnglish: 'the Eastern Republic of Uruguay',
    id: '240',
    contactNoLength: '10',
  },
  {
    countryName: 'US',
    dialCode: '+1',
    isO3: 'USA',
    isO2: 'US',
    untermEnglish: 'the United States of America',
    id: '239',
    contactNoLength: '10',
  },
  {
    countryName: 'Uzbekistan',
    dialCode: '+998',
    isO3: 'UZB',
    isO2: 'UZ',
    untermEnglish: 'the Republic of Uzbekistan',
    id: '241',
    contactNoLength: '10',
  },
  {
    countryName: 'Vanuatu',
    dialCode: '+678',
    isO3: 'VUT',
    isO2: 'VU',
    untermEnglish: 'the Republic of Vanuatu',
    id: '242',
    contactNoLength: '10',
  },
  {
    countryName: 'Vatican City',
    dialCode: '+39-06',
    isO3: 'VAT',
    isO2: 'VA',
    untermEnglish: 'the Holy See',
    id: '103',
    contactNoLength: '10',
  },
  {
    countryName: 'Venezuela',
    dialCode: '+58',
    isO3: 'VEN',
    isO2: 'VE',
    untermEnglish: 'the Bolivarian Republic of Venezuela',
    id: '243',
    contactNoLength: '10',
  },
  {
    countryName: 'Vietnam',
    dialCode: '+84',
    isO3: 'VNM',
    isO2: 'VN',
    untermEnglish: 'the Socialist Republic of Viet Nam',
    id: '244',
    contactNoLength: '10',
  },
  {
    countryName: 'Wallis & Futuna',
    dialCode: '+681',
    isO3: 'WLF',
    isO2: 'WF',
    untermEnglish: '',
    id: '245',
    contactNoLength: '10',
  },
  {
    countryName: 'Western Sahara',
    dialCode: '+212',
    isO3: 'ESH',
    isO2: 'EH',
    untermEnglish: '',
    id: '246',
    contactNoLength: '10',
  },
  {
    countryName: 'Yemen',
    dialCode: '+967',
    isO3: 'YEM',
    isO2: 'YE',
    untermEnglish: 'the Republic of Yemen',
    id: '247',
    contactNoLength: '10',
  },
  {
    countryName: 'Zambia',
    dialCode: '+260',
    isO3: 'ZMB',
    isO2: 'ZM',
    untermEnglish: 'the Republic of Zambia',
    id: '248',
    contactNoLength: '10',
  },
  {
    countryName: 'Zimbabwe',
    dialCode: '+263',
    isO3: 'ZWE',
    isO2: 'ZW',
    untermEnglish: 'the Republic of Zimbabwe',
    id: '249',
    contactNoLength: '10',
  },
];

const MobileNumberInput = (props: IMobileNumberInput) => {
  const {
    selectedCountryCode = '+91',
    label = '',
    countryCode = true,
    // eslint-disable-next-line @typescript-eslint/no-empty-function
    onChangeMobileNumber = () => {},
    // eslint-disable-next-line @typescript-eslint/no-empty-function
    onBlur = () => {},
    errorMessage = '',
    options = countries,
    isDropdown = false,
    controlProps,
    contactNoLen = 15,
    isClear = true,
    classname = '',
    name = '',
    value,
    enableSend,
    sendTxt,
    sendOTP,
    mobileError,
    setMobileError,
    // eslint-disable-next-line react-hooks/rules-of-hooks
    inputRef = useRef(null), //NOSONAR
    setEnableSend,
    disableInfo=false
  } = props;

  const [phoneNumber, setPhoneNumber] = useState('');
  const [countryDropDown, setCountryDropDown] = useState(false);
  const countryLabel = useRef<HTMLDivElement>(null);
  const { deviceType } = useDeviceType();
  const [selectedCountry, setSelectedCountry] = useState<ICountryFlag>();

  useEffect(() => {
    setPhoneNumber(value ?? '');
  }, [value]);

  useEffect(() => {
    setSelectedCountry(
      options?.find(
        (country: ICountryFlag) => country.dialCode.replace('+', '') === selectedCountryCode.replace('+', ''),
      ),
    );
  }, [options, selectedCountryCode]);

  const handlePhoneNumber = (e: { target: { value: string } }, passedValue = '') => {
    const value = e?.target?.value || passedValue;
    const re = /^[0-9\b]+$/;
    if ((value === '' || re.test(value)) && value.length <= contactNoLen) {
      onChangeMobileNumber({
        phoneNumber: value,
        countryCode: selectedCountry?.dialCode ?? '',
        alpha2Code: selectedCountry?.isO2 ?? '',
      });
    }
  };

  const handleSendBtn = (e: { target: { value: string } }) => {
    const value = e?.target?.value;
    if(value.length < contactNoLen){
      setEnableSend(false);
    }
    else{
      setEnableSend(true);
    }
  }

  const selectCountry = (item: ICountryFlag) => {
    setCountryDropDown(false);
    setSelectedCountry(item);
    onChangeMobileNumber({
      phoneNumber: phoneNumber,
      countryCode: item?.dialCode,
      alpha2Code: item?.isO2,
    });
  };

  const onCountryInputClick = () => {
    if (deviceType === 'mobile') {
      setCountryDropDown(true);
    } else {
      setCountryDropDown((prev) => !prev);
    }
  };

  const resetMobileNumber = () => {
    onChangeMobileNumber({ phoneNumber: '' });
    setPhoneNumber('');
  };

  return (
    <div className={`${styles.wrapper} ${errorMessage ? styles.error : ''} ${classname}`}>
      <div className="position-relative">
        <div>
          <div className={styles.combineOption}>
            {countryCode ? (
              <div //NOSONAR
                className={styles.countryCode}
                ref={countryLabel}
                role="button"
                onKeyDown={() => isDropdown && onCountryInputClick()}
                onClick={() => isDropdown && onCountryInputClick()}
              >
                <div className={styles.selectFlag}>
                  <CountrySpriteImage code={selectedCountry?.isO2} />
                  <input
                    className={styles.countryInputFlag}
                    type="text"
                    autoComplete="off"
                    aria-label="Select country code"
                    value={selectedCountry?.dialCode ?? ''}
                    readOnly={true}
                  />
                </div>
                {isDropdown ? (
                  <div className={`${styles.icon} ${countryDropDown ? styles.arrowUp : ''}`}>
                    <CustomIcon iconName="up" />
                  </div>
                ) : (
                  ''
                )}
              </div>
            ) : (
              ''
            )}
            <div className={styles.numWrap}>
              <FloatingInput
                controlProps={{
                  ...controlProps,
                  value: phoneNumber,
                  autoComplete: 'new-password',
                }}
                onChange={(e: any) => {
                  handlePhoneNumber(e);
                  handleSendBtn(e);
                  setMobileError('');
                }}
                onBlur={onBlur}
                name={name}
                inputRef={inputRef}
                inputType="tel"
                label={label || 'Enter Mobile Number'}
                placeholder="Enter Mobile Number"
                classname={styles.mobileInput}
                borderOnFocus={false}
                onClear={resetMobileNumber}
                isClear={isClear}
                disabled={disableInfo}
              />
              {!disableInfo && <button className={`${styles.SendOTP} ${enableSend? '' : styles.disabled}`} disabled={!enableSend} onClick={sendOTP} >{sendTxt}</button>}
              {disableInfo && <button className={styles.Verified}>Verified
              <Image
              src={greenTick}
              alt="Verified"
            />
              </button>}
            </div>
          </div>
        </div>
        
        {(errorMessage || mobileError) && <Error errorMessage={errorMessage ? errorMessage : mobileError} />}
        {isDropdown && countryDropDown && (
          <CountryFlagDropdown
            selectedCountry={selectedCountry}
            countryLabel={countryLabel}
            setCountryDropDown={setCountryDropDown}
            options={options}
            selectCountry={selectCountry}
          />
        )}
      </div>
    </div>
  );
};

export default MobileNumberInput;
